name: predictdb-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12  # Current stable version with good scientific package support
  - numpy>=1.26.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - scipy>=1.11.0
  - snakemake>=7.32.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - sqlite>=3.45.0
  - pip>=23.0.0
  # Optional but recommended for better performance
  - numba>=0.58.0  # For accelerated numerical computing on M3
  - pytables>=3.8.0  # For efficient HDF5 file handling